export enum CancelReason {
  PROVIDER_CHANGE_OF_MIND = 'PROVIDER_CHANGE_OF_MIND',
  PROVIDER_FOUND_OTHER_WAY = 'PROVIDER_FOUND_OTHER_WAY',
  WORKER_NO_SHOW = 'WORKER_NO_SHOW',
  WORKER_EMERGENCY = 'WORKER_EMERGENCY',
  WORKER_WEATHER = 'WORKER_WEATHER',
  ADMIN_FORCE_CANCEL = 'ADMIN_FORCE_CANCEL',
}
